version: '3.9'

services:
  app:
    image: python:3.11.2-slim-bullseye
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9090:5000
    volumes:
      - todolist.db:/home/worker/app/db
volumes:
  todolist.db:
