name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
#        uses: docker/login-action@v2
        run:  docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: example-app:latest

#    steps:
#    - uses: actions/checkout@v3
    
#    - name: Login to docker-hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#      run:  docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}

#    - name: Build and push
#      uses: docker/build-push-action@v4
#      with:
#        push: true
#        tags: agus3yoga/todo-app:latest
#    - name: Build docker-image
#      run: docker build -t agus3yoga/todo-app:latest .
    
#    - name: Tag docker-image
#      run: docker tag $(docker images -aq | head -n1) ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
    
      
#    - name: Push to registry
#      run: docker push agus3yoga/todo-app:latest
